#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh ps.h /Tps_3_0 simple.fx /EPS
//
//
// Parameters:
//
//   sampler2D TextureSampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   TextureSampler s0       1
//

// Shader type: pixel 

xps_3_0
defconst TextureSampler, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1


    exec
    tfetch2D r1, r0.xy, tf0
    alloc colors
    exece
    mov oC0, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_PS[] =
{
    0x102a1100, 0x000000b4, 0x0000003c, 0x00000000, 0x00000024, 0x00000000, 
    0x0000008c, 0x00000000, 0x00000000, 0x00000064, 0x0000001c, 0x00000057, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000050, 0x00000030, 
    0x00030000, 0x00010000, 0x00000040, 0x00000000, 0x54657874, 0x75726553, 
    0x616d706c, 0x657200ab, 0x0004000c, 0x00010001, 0x00010000, 0x00000000, 
    0x70735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 
    0x0000003c, 0x10000100, 0x00000008, 0x00000000, 0x00001842, 0x00010003, 
    0x00000001, 0x00003050, 0x0000f1a0, 0x00011002, 0x00001200, 0xc4000000, 
    0x00001003, 0x00002200, 0x00000000, 0x10081001, 0x1f1ff688, 0x00004000, 
    0xc80f8000, 0x00000000, 0xe2010100, 0x00000000, 0x00000000, 0x00000000
};
