#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh vs.h /Tvs_3_0 simple.fx /EVS
//
// Shader type: vertex 

xvs_3_0
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1
// VsExportCount=1

dcl_index r0.x
dcl_texcoord o0.xy
dcl_color o1


    exec
    vfetch r2, r0.x, position
    vfetch r1, r0.x, color
    vfetch r0.xy__, r0.x, texcoord
    alloc position
    exec
    mov oPos, r2
    alloc interpolators
    exece
    mov o0.xy, r0.xy
    mov o1, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VS[] =
{
    0x102a1101, 0x0000009c, 0x00000078, 0x00000000, 0x00000024, 0x00000000, 
    0x00000058, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xfffe0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x76735f33, 
    0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 0x00000078, 
    0x00110002, 0x00000000, 0x00000000, 0x00001842, 0x00000001, 0x00000003, 
    0x00000002, 0x00000290, 0x00100003, 0x0000a004, 0x00305005, 0x00003050, 
    0x0001f1a0, 0x00001007, 0x00001008, 0x70153003, 0x00001200, 0xc2000000, 
    0x00001006, 0x00001200, 0xc4000000, 0x00002007, 0x00002200, 0x00000000, 
    0x05f82000, 0x00000688, 0x00000000, 0x05f81000, 0x00000688, 0x00000000, 
    0x05f80000, 0x00000fc8, 0x00000000, 0xc80f803e, 0x00000000, 0xe2020200, 
    0xc8038000, 0x00b0b000, 0xe2000000, 0xc80f8001, 0x00000000, 0xe2010100, 
    0x00000000, 0x00000000, 0x00000000
};
